##肉類
#豬肉=0
pork__repeatchoose=0.1
#魚肉
fish__repeatchoose=0.1
#雞肉
chicken__repeatchoose=0.1
#鴨肉
duck__repeatchoose=0.1

###青菜類
##葉菜類
#高麗菜
cabbage__repeatchoose=0.1
#菠菜
spinach__repeatchoose=0.1
#青江菜
ching_chiang__repeatchoose=0.1
#芹菜
celery__repeatchoose=0.1
#空心菜
con_sin__repeatchoose=0.1
#大白菜
brassica_rapa_pekinensis__repeatchoose=0.1
#地瓜葉
sweet_potato_leaves__repeatchoose=0.1
##瓜果類
#絲瓜
loofah__repeatchoose=0.1
#冬瓜
benincasa_pruriens__repeatchoose=0.1
#苦瓜
bitter__repeatchoose=0.1
#玉米
corn__repeatchoose=0.1
#秋葵
okra__repeatchoose=0.1
##根菜類
#玉米筍
young_corn__repeatchoose=0.1
#蘿蔔
radish__repeatchoose=0.1
#馬鈴薯
potato__repeatchoose=0.1
#紅蘿蔔
carrot__repeatchoose=0.1
#竹筍
bamboo_shoot__repeatchoose=0.1
##花菜類
#花椰菜
cauliflower__repeatchoose=0.1
